# -*- coding: utf-8 -*-
"""scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ZTc1PaaXexvhjKpqxZsXsgQ4eDmzzJW
"""

import requests
from bs4 import BeautifulSoup

r=requests.get('https://www.property.com.mm/index.php/en')
c=r.content
c

soup=BeautifulSoup(c,'html.parser')
print(soup.prettify)

# all=soup.find_all("div",{"class":"cl-gallery"})
all = soup.find_all("article", class_="aa-properties-item")

all

len(all)

all[0].find_all("p",{"class":"displayaddress"})

all[0].find("p",{"class":"displayaddress"}).text.replace("\n","")

all[2].find("span",{'class','aa-price'}).text

all[2].find("p",{'class','featured-option_2'}).text

print(item.prettify())

l=[]
base_url="https://property.com.mm/index.php/en/6/browse"
for page in range(0,60,10):
  url=base_url+str(page)
  print("Scraping:",url)

  r=requests.get(url)
  c=r.content
  soup=BeautifulSoup(c,"html.parser")

  all=soup.find_all("article", class_="aa-properties-item")
  print("Listings on this page:",len(all))

  for item in all:
    d={}
    try:
         price_tag = item.find("span", class_="aa-price")
         d["Price"] = price_tag.text.strip() if price_tag else "N/A"

         address_tag = item.find("p", class_="displayaddress")
         d["Address"] = address_tag.text.strip() if address_tag else "N/A"

         type_tag = item.find("p", class_="featured-option_2")
         d["Type"] = type_tag.text.strip() if type_tag else "N/A"


         room_icon=item.find("img",alt="Total Rooms")
         d['Rooms']=room_icon.parent.text.strip() if room_icon else "0"

         bed_icon = item.find("img", alt="Total Bedrooms")
         d["Bedrooms"] = bed_icon.parent.text.strip() if bed_icon else "0"


         l.append(d)
    except Exception as e:
      continue

  print(f"Total Listing collected:{len(l)}")

import pandas
df=pandas.DataFrame(l)

df

base_url="https://property.com.mm/index.php/en/6/browse"
for page in range(0,60,10):
  print(base_url+str(page))
  # r=requests.get(base_url+str(page))
  # c=r.content
  # soup=BeautifulSoup(c,"html.parser")
  # print(soup.prettify)

df.to_csv("output.csv")

import pandas as pd
df=pd.read_csv("output.csv")
df.head()