# -*- coding: utf-8 -*-
"""datacleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z96WtOSm1l-BZ4sn1708CO4ws0FTWkDJ
"""

import requests
from bs4 import BeautifulSoup

r=requests.get('https://www.property.com.mm/index.php/en')
c=r.content
c

soup=BeautifulSoup(c,'html.parser')
print(soup.prettify)

# all=soup.find_all("div",{"class":"cl-gallery"})
all = soup.find_all("article", class_="aa-properties-item")

all

len(all)

all[0].find_all("p",{"class":"displayaddress"})

all[0].find("p",{"class":"displayaddress"}).text.replace("\n","")

all[2].find("span",{'class','aa-price'}).text

all[2].find("p",{'class','featured-option_2'}).text

print(item.prettify())

l=[]
base_url="https://property.com.mm/index.php/en/6/browse"
for page in range(0,60,10):
  url=base_url+str(page)
  print("Scraping:",url)

  r=requests.get(url)
  c=r.content
  soup=BeautifulSoup(c,"html.parser")

  all=soup.find_all("article", class_="aa-properties-item")
  print("Listings on this page:",len(all))

  for item in all:
    d={}
    try:
         price_tag = item.find("span", class_="aa-price")
         d["Price"] = price_tag.text.strip() if price_tag else "N/A"

         address_tag = item.find("p", class_="displayaddress")
         d["Address"] = address_tag.text.strip() if address_tag else "N/A"

         type_tag = item.find("p", class_="featured-option_2")
         d["Type"] = type_tag.text.strip() if type_tag else "N/A"


         room_icon=item.find("img",alt="Total Rooms")
         d['Rooms']=room_icon.parent.text.strip() if room_icon else "0"

         bed_icon = item.find("img", alt="Total Bedrooms")
         d["Bedrooms"] = bed_icon.parent.text.strip() if bed_icon else "0"


         l.append(d)
    except Exception as e:
      continue

  print(f"Total Listing collected:{len(l)}")

import pandas
df=pandas.DataFrame(l)

df

base_url="https://property.com.mm/index.php/en/6/browse"
for page in range(0,60,10):
  print(base_url+str(page))
  # r=requests.get(base_url+str(page))
  # c=r.content
  # soup=BeautifulSoup(c,"html.parser")
  # print(soup.prettify)

df.to_csv("output.csv")

import pandas as pd
df=pd.read_csv("output.csv")
df.head()

"""#Clean Data"""

import pandas as pd
import re

def parse_price(price):
    if pd.isna(price):
        return pd.Series([None, None])

    price = str(price).replace("|", "").strip()

    if "USD" in price:
        currency = "USD"
        number = re.findall(r"\d+(?:\.\d+)?", price)
        value = float(number[0]) if number else None

    elif "Lkhs" in price:
        currency = "Lkhs"
        number = re.findall(r"\d+(?:\.\d+)?", price)
        value = float(number[0]) if number else None

    else:
        currency = "Unknown"
        number = re.findall(r"\d+(?:\.\d+)?", price)
        value = float(number[0]) if number else None

    return pd.Series([currency, value])

df[["Currency", "Price_Value"]] = df["Price"].apply(parse_price)

print(df[["Price", "Currency", "Price_Value"]].head())

"""#Currency"""

# Step 1: Clean raw string
df["Price_Clean"] = df["Price"].astype(str).str.replace("|", "", regex=False).str.strip()

# Step 2: Extract currency FIRST
df["Currency"] = df["Price_Clean"].apply(
    lambda x: "USD" if "USD" in str(x)
    else "Lkhs" if "Lkhs" in str(x)
    else "Unknown"
)

# Step 3: Extract numeric value
df["Price_Value"] = df["Price_Clean"].str.extract(r"(\d+(?:\.\d+)?)").astype(float)

print(df["Price"].head())
print(df["Price"].dtype)

df = pd.read_csv("output.csv")

import pandas as pd

df = pd.read_csv("output.csv")

df["Price_Raw"] = df["Price"].astype(str)
df["Price_Clean"] = df["Price_Raw"].str.replace("|", "", regex=False).str.strip()

df["Currency"] = df["Price_Clean"].apply(
    lambda x: "USD" if "USD" in x
    else "Lkhs" if "Lkhs" in x
    else "Unknown"
)

df["Price_Value"] = df["Price_Clean"].str.extract(r"(\d+(?:\.\d+)?)").astype(float)

print(df[["Price", "Price_Clean", "Currency", "Price_Value"]].head())

"""#Check data quality"""

print(df.info())
print(df.isnull().sum())
print(df["Currency"].value_counts())
print(df["Type"].value_counts())
print(df["Bedrooms"].value_counts())
print(df["Rooms"].value_counts())

df[df["Price_Value"].isnull()]
df[df["Bedrooms"] == 0].head(10)

df_usd = df[df["Currency"] == "USD"].copy()
df_lkhs = df[df["Currency"] == "Lkhs"].copy()

print(df_usd[["Price", "Price_Value"]].head())
print(df_lkhs[["Price", "Price_Value"]].head())

"""#clean numeric columns"""

df["Rooms"] = pd.to_numeric(df["Rooms"], errors="coerce")
df["Bedrooms"] = pd.to_numeric(df["Bedrooms"], errors="coerce")

print(df[["Rooms", "Bedrooms"]].describe())