# -*- coding: utf-8 -*-
"""Simple_Analysis _Visualize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BuD06IiDFvsgevnbXsnpe8sy5SX4C_jy

#Scraper
"""

import requests
from bs4 import BeautifulSoup

r=requests.get('https://www.property.com.mm/index.php/en')
c=r.content
c

soup=BeautifulSoup(c,'html.parser')
print(soup.prettify)

# all=soup.find_all("div",{"class":"cl-gallery"})
all = soup.find_all("article", class_="aa-properties-item")

all

len(all)

all[0].find_all("p",{"class":"displayaddress"})

all[0].find("p",{"class":"displayaddress"}).text.replace("\n","")

all[2].find("span",{'class','aa-price'}).text

all[2].find("p",{'class','featured-option_2'}).text

print(item.prettify())

l=[]
base_url="https://property.com.mm/index.php/en/6/browse"
for page in range(0,60,10):
  url=base_url+str(page)
  print("Scraping:",url)

  r=requests.get(url)
  c=r.content
  soup=BeautifulSoup(c,"html.parser")

  all=soup.find_all("article", class_="aa-properties-item")
  print("Listings on this page:",len(all))

  for item in all:
    d={}
    try:
         price_tag = item.find("span", class_="aa-price")
         d["Price"] = price_tag.text.strip() if price_tag else "N/A"

         address_tag = item.find("p", class_="displayaddress")
         d["Address"] = address_tag.text.strip() if address_tag else "N/A"

         type_tag = item.find("p", class_="featured-option_2")
         d["Type"] = type_tag.text.strip() if type_tag else "N/A"


         room_icon=item.find("img",alt="Total Rooms")
         d['Rooms']=room_icon.parent.text.strip() if room_icon else "0"

         bed_icon = item.find("img", alt="Total Bedrooms")
         d["Bedrooms"] = bed_icon.parent.text.strip() if bed_icon else "0"


         l.append(d)
    except Exception as e:
      continue

  print(f"Total Listing collected:{len(l)}")

import pandas
df=pandas.DataFrame(l)

df

base_url="https://property.com.mm/index.php/en/6/browse"
for page in range(0,60,10):
  print(base_url+str(page))
  # r=requests.get(base_url+str(page))
  # c=r.content
  # soup=BeautifulSoup(c,"html.parser")
  # print(soup.prettify)

df.to_csv("output.csv")

import pandas as pd
df=pd.read_csv("output.csv")
df.head()

"""#Clean Data"""

import pandas as pd
import re

def parse_price(price):
    if pd.isna(price):
        return pd.Series([None, None])

    price = str(price).replace("|", "").strip()

    if "USD" in price:
        currency = "USD"
        number = re.findall(r"\d+(?:\.\d+)?", price)
        value = float(number[0]) if number else None

    elif "Lkhs" in price:
        currency = "Lkhs"
        number = re.findall(r"\d+(?:\.\d+)?", price)
        value = float(number[0]) if number else None

    else:
        currency = "Unknown"
        number = re.findall(r"\d+(?:\.\d+)?", price)
        value = float(number[0]) if number else None

    return pd.Series([currency, value])

df[["Currency", "Price_Value"]] = df["Price"].apply(parse_price)

print(df[["Price", "Currency", "Price_Value"]].head())

"""## Currency"""

# Step 1: Clean raw string
df["Price_Clean"] = df["Price"].astype(str).str.replace("|", "", regex=False).str.strip()

# Step 2: Extract currency FIRST
df["Currency"] = df["Price_Clean"].apply(
    lambda x: "USD" if "USD" in str(x)
    else "Lkhs" if "Lkhs" in str(x)
    else "Unknown"
)

# Step 3: Extract numeric value
df["Price_Value"] = df["Price_Clean"].str.extract(r"(\d+(?:\.\d+)?)").astype(float)

print(df["Price"].head())
print(df["Price"].dtype)

df = pd.read_csv("output.csv")

import pandas as pd

df = pd.read_csv("output.csv")

df["Price_Raw"] = df["Price"].astype(str)
df["Price_Clean"] = df["Price_Raw"].str.replace("|", "", regex=False).str.strip()

df["Currency"] = df["Price_Clean"].apply(
    lambda x: "USD" if "USD" in x
    else "Lkhs" if "Lkhs" in x
    else "Unknown"
)

df["Price_Value"] = df["Price_Clean"].str.extract(r"(\d+(?:\.\d+)?)").astype(float)

print(df[["Price", "Price_Clean", "Currency", "Price_Value"]].head())

"""## Convert to One Currency"""

import numpy as np
USD_TO_LKHS = 2100 / 100000  # example: convert USD → Lkhs (adjust if needed)

df["Price_Lkhs"] = np.where(
    df["Currency"] == "USD",
    df["Price_Value"] * USD_TO_LKHS,
    df["Price_Value"]
)

"""##Check data quality"""

print(df.info())
print(df.isnull().sum())
print(df["Currency"].value_counts())
print(df["Type"].value_counts())
print(df["Bedrooms"].value_counts())
print(df["Rooms"].value_counts())

df[df["Price_Value"].isnull()]
df[df["Bedrooms"] == 0].head(10)

df_usd = df[df["Currency"] == "USD"].copy()
df_lkhs = df[df["Currency"] == "Lkhs"].copy()

print(df_usd[["Price", "Price_Value"]].head())
print(df_lkhs[["Price", "Price_Value"]].head())

"""##clean Rooms and Bedrooms"""

df["Rooms"] = pd.to_numeric(df["Rooms"], errors="coerce")
df["Bedrooms"] = pd.to_numeric(df["Bedrooms"], errors="coerce")

"""Handle Missing"""

df["Rooms"].fillna(df["Rooms"].median(), inplace=True)
df["Bedrooms"].fillna(df["Bedrooms"].median(), inplace=True)

print(df[["Rooms", "Bedrooms"]].describe())

"""## Clean Categorical columns"""

df["Type"] = df["Type"].str.strip().fillna("Unknown")

df = pd.get_dummies(df, columns=["Type"], drop_first=True)

"""Remove Useless columns"""

df_clean = df[[
    "Price_Lkhs",
    "Rooms",
    "Bedrooms"
] + [col for col in df.columns if col.startswith("Type_")]]

"""Handle Outliers for ML"""

df_clean = df_clean[df_clean["Price_Lkhs"] < df_clean["Price_Lkhs"].quantile(0.99)]

for col in df_clean.columns:
    if df_clean[col].dtype == 'bool':
        df_clean[col] = df_clean[col].astype(int)

"""Final Check"""

print(df_clean.info())
print(df_clean.describe())
print(df_clean.isnull().sum())

df_clean.to_csv("ml_ready_properties.csv", index=False)

"""#Simple Analysis

###Average Price by type
"""

df.groupby("Type")["Price_Value"].mean()

"""###Aveage bedrooms by *type*"""

df.groupby("Type")["Bedrooms"].mean()

"""### Most expensive properties"""

df.sort_values("Price_Value", ascending=False)[["Price", "Address", "Type","Rooms", "Bedrooms"]].head(20)

"""#Visualize"""

import matplotlib.pyplot as plt

df_lkhs["Price_Value"].hist()
plt.title("Price Distribution (Lkhs)")
plt.xlabel("Price")
plt.ylabel("Count")
plt.show()

df["Type"].value_counts().plot(kind="bar")
plt.title("Property Types")
plt.xlabel("Type")
plt.ylabel("Count")
plt.show()

"""##Questions:
* Which property type is most |common?
* Which listings have the highest price?
* Do flats have fewer bedrooms than landed houses?
* Are large-room properties always more expensive?
"""

import numpy as np

df["Price_per_room"] = np.where(df["Rooms"] > 0, df["Price_Value"] / df["Rooms"], np.nan)
df["Price_per_bedroom"] = np.where(df["Bedrooms"] > 0, df["Price_Value"] / df["Bedrooms"], np.nan)

df["Price_Value"] = pd.to_numeric(df["Price_Value"], errors="coerce")
df["Rooms"] = pd.to_numeric(df["Rooms"], errors="coerce")
df["Bedrooms"] = pd.to_numeric(df["Bedrooms"], errors="coerce")

# Optional: remove rows with missing essential values
analysis_df = df.dropna(subset=["Type", "Price_Value"]).copy()

print("1. Which property type is most common?")
type_counts = analysis_df["Type"].value_counts()
print(type_counts)
print("\nMost common property type:", type_counts.idxmax())

# 2. Which listings have the highest price?

print("\n2. Which listings have the highest price?")

highest_price_listings = analysis_df.sort_values("Price_Value", ascending=False)[
    ["Price", "Currency", "Price_Value", "Address", "Type", "Rooms", "Bedrooms"]
].head(15)

print(highest_price_listings)

# 3. Do flats have fewer bedrooms than landed houses?

print("\n3. Do flats have fewer bedrooms than landed houses?")

bedroom_compare = analysis_df[analysis_df["Type"].isin(["Flat", "Landed House"])].groupby("Type")["Bedrooms"].mean()
print(bedroom_compare)

if "Flat" in bedroom_compare.index and "Landed House" in bedroom_compare.index:
    if bedroom_compare["Flat"] < bedroom_compare["Landed House"]:
        print("\nYes, flats have fewer bedrooms on average than landed houses.")
    elif bedroom_compare["Flat"] > bedroom_compare["Landed House"]:
        print("\nNo, flats have more bedrooms on average than landed houses.")
    else:
        print("\nFlats and landed houses have the same average number of bedrooms.")
else:
    print("\nNot enough data for both Flat and Landed House.")

# 4. Are large-room properties always more expensive?

print("\n4. Are large-room properties always more expensive?")

# Average price by number of rooms
room_price_summary = analysis_df.groupby("Rooms")["Price_Value"].mean().sort_index()
print(room_price_summary)

# Correlation between Rooms and Price_Value
corr = analysis_df[["Rooms", "Price_Value"]].corr().loc["Rooms", "Price_Value"]
print(f"\nCorrelation between Rooms and Price_Value: {corr:.2f}")

if corr > 0:
    print("There is a positive relationship: more rooms tend to have higher prices.")
else:
    print("There is not a positive relationship between more rooms and higher prices.")

# Check if price always increases as rooms increase
is_always_increasing = room_price_summary.is_monotonic_increasing

if is_always_increasing:
    print("Yes, based on average prices, larger-room properties are always more expensive.")
else:
    print("No, larger-room properties are not always more expensive.")

# Line chart
room_price_summary.plot(marker="o")
plt.title("Average Price by Number of Rooms")
plt.xlabel("Rooms")
plt.ylabel("Average Price")
plt.show()

